spring:
  application:
    name: web app
  IPAddress: <address1>, <address2>
  security:
    jwt:
      secret: <secret>
      secure: <boolean>
    user:
      name: <username>
      password: <password>
  datasource:
    url: jdbc:<server-type>://<address>:<port>/<database><options>
    username: <username>
    password: <password>
    driver-class-name: <package>.<class>

server:
  port: 443
  ssl:
    enabled: true
    key-store: <classpath:path/to/keystore.jks>
    key-store-password: <password>
    key-store-type: JKS
